language: rust

matrix:
  include:
      # MSRV
    - env: T=x86_64-unknown-linux-gnu
      rust: 1.34.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

      # 64-bit
    - env: T=x86_64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

      # 32-bit
    - env: T=i686-unknown-linux-musl
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

      # no panics in generated code
    - env: T=thumbv7m-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install:
  - set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cache

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
