[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "ufmt-utils"
version = "0.1.0-alpha.1"

[dependencies]
heapless = "0.5.0-alpha.2"
ufmt-write = { version = "0.1.0-beta.1", path = "../write" }
