[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "ufmt-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.12"

[dependencies.syn]
features = ["full"]
version = "0.15.33"
